version: '3.9'
services:
  db:
    image: mongo:4.2
    container_name: todo-list_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - todo-network

  db_ui:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    container_name: todo-list_mongo_express
    ports:
      - ${PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/
      ME_CONFIG_MONGODB_AUTH_MECHANISM: SCRAM-SHA-256
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:

